"""Slot mapping, G-code header and order body helpers (PROTOCOL B §5, D §2)."""

from __future__ import annotations

import pytest

from anycubic_cloud_client import (
    GcodeMetadataError,
    Order,
    OrderShape,
    PaintInfo,
    SlotMappingError,
    build_order_body,
    build_slot_mapping,
    gcode_colors,
    parse_gcode_header,
)
from anycubic_cloud_client.models import parse_ace_units
from anycubic_cloud_client.orders import ORDER_SHAPES, shape_for
from anycubic_cloud_client.printing import ams_info, validate_slots

# -- order shapes -----------------------------------------------------------------------


def test_order_shape_table() -> None:
    string_ids = {1231, 1232, 1001, 201, 1213, 1216, 1221, 1243}
    for order, shape in ORDER_SHAPES.items():
        body = build_order_body(
            5, order, data={"x": 1} if shape is OrderShape.PROJECT else None
        )
        assert isinstance(body["order_id"], str) == (order in string_ids), order
        assert ("project_id" in body) == (
            shape
            in (OrderShape.PROJECT, OrderShape.BARE_PROJECT, OrderShape.PRINT_CONTROL)
        ), order
    assert shape_for(Order.SET_LIGHT_STATUS, None) is OrderShape.PRINTER
    assert shape_for(Order.SET_LIGHT_STATUS, 3) is OrderShape.PROJECT


def test_order_body_defaults() -> None:
    assert build_order_body(5, 201) == {
        "order_id": "201",
        "printer_id": 5,
        "data": None,
    }
    assert build_order_body(5, 103) == {
        "order_id": 103, "printer_id": 5, "project_id": 0, "data": {}}  # fmt: skip
    assert build_order_body(5, 1) == {
        "order_id": 1, "printer_id": 5, "project_id": 0, "data": None,
        "ams_info": None, "settings": None}  # fmt: skip
    assert build_order_body(5, 1001) == {
        "order_id": "1001", "printer_id": 5, "shengwang_rtc_support": True}  # fmt: skip


# -- slot mapping (PROTOCOL D §2.4) -------------------------------------------------------


def _units(first_id: int = 0) -> tuple:  # type: ignore[type-arg]
    return parse_ace_units(
        [
            {"id": first_id, "slots": [
                {"index": 0, "color": [10, 10, 10]}, {"index": 1, "color": [11, 11, 11]},
                {"index": 2, "color": [12, 12, 12]}, {"index": 3, "color": [13, 13, 13]}]},
            {"id": first_id + 1, "slots": [
                {"index": 0, "color": [20, 20, 20]}, {"index": 2, "color": [22, 22, 22]}]},
        ]
    )  # fmt: skip


def _colors(*indexes: int) -> list[PaintInfo]:
    return [
        PaintInfo(paint_index=i, material_type=f"M{i}", filament_used=float(i) + 0.5)
        for i in indexes
    ]


@pytest.mark.parametrize("first_id", [0, 1])
def test_mapping_works_with_either_first_box_id(first_id: int) -> None:
    # INTEGRATION-SPEC §11 / Q2: box 0 reported as id 0 or id 1.
    mapping = build_slot_mapping(_colors(2, 0, 1), [4, 1, 6], _units(first_id))
    assert [(m.paint_index, m.ams_index) for m in mapping] == [(0, 1), (1, 6), (2, 4)]
    assert mapping[0].ams_color == (11, 11, 11)
    assert mapping[1].ams_color == (22, 22, 22)
    assert mapping[2].material_type == "M2" and mapping[2].filament_used == 2.5


def test_mapping_uses_the_files_paint_colour() -> None:
    colors = [PaintInfo(paint_index=0, material_type="PLA", paint_color=(1, 2, 3))]
    (entry,) = build_slot_mapping(colors, [0], _units())
    assert entry.ams_color == (10, 10, 10)
    assert entry.paint_color == (1, 2, 3)
    assert entry.to_data() == {
        "ams_color": [10, 10, 10],
        "ams_index": 0,
        "filament_used": None,
        "material_type": "PLA",
        "paint_color": [1, 2, 3],
        "paint_index": 0,
    }


@pytest.mark.parametrize(
    ("slots", "message"),
    [
        ([0], "2 colours"),
        ([0, -1], "start at 0"),
        ([0, 8], "not enough ACE"),
        ([0, 5], "no known colour"),
    ],
)
def test_mapping_errors(slots: list[int], message: str) -> None:
    with pytest.raises(SlotMappingError, match=message):
        build_slot_mapping(_colors(0, 1), slots, _units())


def test_validate_slots_and_ams_info() -> None:
    validate_slots(None, ())
    validate_slots([0], _units())
    with pytest.raises(SlotMappingError, match="has an ACE"):
        validate_slots(None, _units())
    with pytest.raises(SlotMappingError, match="no ACE"):
        validate_slots([0], ())
    assert ams_info([]) is None
    info = ams_info(build_slot_mapping(_colors(0), [2], _units()))
    assert info is not None and info["use_ams"] is True


# -- G-code header (PROTOCOL D §2.6) -----------------------------------------------------

HEADER = """; generated by a slicer
; ignored = before the first filament line
; filament used [mm] = 1000.5,300
; filament used [cm3] = 2.4
; filament used [g] = 3.2, 1.1
; total filament change = 4
; paint_info = [{"paint_index": 1, "material_type": "PETG", "extra": true}, {"paint_index": 0, "material_type": "PLA", "paint_color": "#FF0000"}]
; CONFIG_BLOCK_START = begin
; layer_height = 0.2
; printer (model) = Kobra S1
; list = a, 2, 3.5
G1 X0
"""


def test_parse_header() -> None:
    header = parse_gcode_header(HEADER.encode())
    assert "ignored" not in header
    assert header["filament_used_mm"] == [1000.5, 300]
    assert header["filament_used_cm3"] == 2.4
    assert header["filament_used_g"] == [3.2, 1.1]
    assert header["total_filament_change"] == 4
    assert header["layer_height"] == 0.2
    assert header["printer_model"] == "Kobra S1"
    assert header["list"] == ["a", 2, 3.5]
    assert "CONFIG_BLOCK_START" not in header
    assert isinstance(header["paint_info"], list)


def test_colors_by_paint_index() -> None:
    colors = gcode_colors(parse_gcode_header(HEADER))
    petg, pla = colors
    assert petg.paint.paint_index == 1 and petg.paint.filament_used == 1.1
    assert petg.filament_used_mm == 300
    assert petg.filament_used_cm3 is None  # the cm3 list is shorter
    assert petg.raw["extra"] is True
    assert pla.paint.filament_used == 3.2
    assert pla.paint.paint_color == (255, 0, 0)
    assert pla.filament_used_cm3 == 2.4


@pytest.mark.parametrize(
    ("header", "message"),
    [
        ({}, "empty paint info"),
        ({"paint_info": [{"paint_index": 0}]}, "filament used"),
        (
            {
                "paint_info": [{"paint_index": 0}, {"paint_index": 1}],
                "filament_used_g": [1.0],
            },
            "shorter",
        ),
        ({"paint_info": ["x"], "filament_used_g": [1.0]}, "not an object"),
        ({"paint_info": [{"paint_index": 3}], "filament_used_g": [1.0]}, "paint_index"),
    ],
)
def test_color_errors(header: dict[str, object], message: str) -> None:
    with pytest.raises(GcodeMetadataError, match=message):
        gcode_colors(header)


def test_single_filament_scalar() -> None:
    header = {
        "paint_info": [{"paint_index": 0, "material_type": "PLA"}],
        "filament_used_g": 2,
    }
    (color,) = gcode_colors(header)
    assert color.paint.filament_used == 2
    assert color.paint.material_type == "PLA"


def test_non_utf8_header() -> None:
    with pytest.raises(GcodeMetadataError, match="UTF-8"):
        parse_gcode_header(b"\xff\xfe; filament used [g] = 1")
