"""Async client for the Anycubic cloud.

This library contains none of Anycubic's credentials: the caller passes them
in a :class:`CloudSecrets`. Typical use::

    secrets = CloudSecrets(app_id=..., app_secret=..., client_id_web=...,
                           client_id_app=..., mqtt_ca_pem=...,
                           mqtt_client_cert_pem=..., mqtt_client_key_pem=...)
    cloud = AnycubicCloudClient.from_entry(
        session, secrets, token=pasted_token, auth_mode=AuthMode.SLICER,
        region=Region.INTERNATIONAL, store=saved_token_store,
    )
    account = await cloud.check()
    printers = await cloud.get_printers()

See ``docs/PROTOCOL.md`` for the protocol and ``docs/INTEGRATION-SPEC.md``
for the requirements this implements.
"""

from __future__ import annotations

from .agora import AgoraCameraSession, choose_server, open_camera_session
from .client import (
    AnycubicCloudClient,
    ApiResponse,
    PrintStartResult,
    SignInResult,
    sign_in_any,
    sign_in_order,
    validate_print_settings,
)
from .credentials import CloudSecrets
from .errors import (
    AgoraError,
    AnycubicCloudError,
    CloudFileNotFoundError,
    CredentialsRejectedError,
    GcodeMetadataError,
    MqttAuthError,
    MqttConnectionError,
    MqttError,
    MqttNotAllowedError,
    MqttNotConnectedError,
    NoCameraCredentialsError,
    OrderRefusedError,
    PrinterRemovedError,
    RejectReason,
    RenameFailedError,
    SecretsInvalidError,
    ServiceUnavailableError,
    SlotMappingError,
    StorageFullError,
    UnexpectedResponseError,
    UploadError,
)
from .firmware import FirmwareProgress
from .messages import (
    AceLoadedSlotUpdate,
    AxisMoveUpdate,
    BindingUpdate,
    CloudMessage,
    ExternalHolderUpdate,
    Fault,
    FileDeletedUpdate,
    FileListUpdate,
    FirmwareReport,
    FirmwareStep,
    JobStatus,
    OnlineUpdate,
    PrinterEvent,
    PrintUpdate,
    WorkStatus,
    WorkStatusUpdate,
    parse_cloud_message,
)
from .models import (
    Account,
    AceSlotInfo,
    AceUnit,
    CameraCredentials,
    CloudFile,
    DryingStatus,
    ExternalHolder,
    FeedStatus,
    FirmwareInfo,
    Function,
    GcodeInfo,
    Job,
    JobDetail,
    JobSettings,
    PaintInfo,
    PrinterDetail,
    PrinterFile,
    PrinterModel,
    PrinterSummary,
    SliceParam,
    SpeedModeOption,
    StorageQuota,
    TempLimits,
    select_latest_job,
)
from .mqtt import CloudMqttClient
from .mqtt_identity import (
    MqttIdentity,
    build_identity,
    mqtt_client_id,
    parse_topic,
    printer_topics,
    redact_topic,
    user_topics,
)
from .orders import (
    Axis,
    FeedType,
    FileSource,
    MoveType,
    Order,
    OrderShape,
    build_order_body,
)
from .printing import (
    GcodeColor,
    SlotAssignment,
    TaskSettings,
    build_slot_mapping,
    gcode_colors,
    parse_gcode_header,
)
from .regions import AuthMode, Region, RegionEndpoints
from .tokens import (
    SignatureCheck,
    SignatureStatus,
    TokenClaims,
    TokenState,
    decode_claims,
    extract_token,
    store_is_stale,
    trim_signature,
    verify_token_signature,
)

__version__ = "0.1.0"

__all__ = [
    "Account",
    "AceLoadedSlotUpdate",
    "AceSlotInfo",
    "AceUnit",
    "AgoraCameraSession",
    "AgoraError",
    "AnycubicCloudClient",
    "AnycubicCloudError",
    "ApiResponse",
    "AuthMode",
    "Axis",
    "AxisMoveUpdate",
    "BindingUpdate",
    "CameraCredentials",
    "CloudFile",
    "CloudFileNotFoundError",
    "CloudMessage",
    "CloudMqttClient",
    "CloudSecrets",
    "CredentialsRejectedError",
    "DryingStatus",
    "ExternalHolder",
    "ExternalHolderUpdate",
    "Fault",
    "FeedStatus",
    "FeedType",
    "FileDeletedUpdate",
    "FileListUpdate",
    "FileSource",
    "FirmwareInfo",
    "FirmwareProgress",
    "FirmwareReport",
    "FirmwareStep",
    "Function",
    "GcodeColor",
    "GcodeInfo",
    "GcodeMetadataError",
    "Job",
    "JobDetail",
    "JobSettings",
    "JobStatus",
    "MoveType",
    "MqttAuthError",
    "MqttConnectionError",
    "MqttError",
    "MqttIdentity",
    "MqttNotAllowedError",
    "MqttNotConnectedError",
    "NoCameraCredentialsError",
    "OnlineUpdate",
    "Order",
    "OrderRefusedError",
    "OrderShape",
    "PaintInfo",
    "PrintStartResult",
    "PrintUpdate",
    "PrinterDetail",
    "PrinterEvent",
    "PrinterFile",
    "PrinterModel",
    "PrinterRemovedError",
    "PrinterSummary",
    "Region",
    "RegionEndpoints",
    "RejectReason",
    "RenameFailedError",
    "SecretsInvalidError",
    "ServiceUnavailableError",
    "SignInResult",
    "SignatureCheck",
    "SignatureStatus",
    "SliceParam",
    "SlotAssignment",
    "SlotMappingError",
    "SpeedModeOption",
    "StorageFullError",
    "StorageQuota",
    "TaskSettings",
    "TempLimits",
    "TokenClaims",
    "TokenState",
    "UnexpectedResponseError",
    "UploadError",
    "WorkStatus",
    "WorkStatusUpdate",
    "__version__",
    "build_identity",
    "build_order_body",
    "build_slot_mapping",
    "choose_server",
    "decode_claims",
    "extract_token",
    "gcode_colors",
    "mqtt_client_id",
    "open_camera_session",
    "parse_cloud_message",
    "parse_gcode_header",
    "parse_topic",
    "printer_topics",
    "redact_topic",
    "select_latest_job",
    "sign_in_any",
    "sign_in_order",
    "store_is_stale",
    "trim_signature",
    "user_topics",
    "validate_print_settings",
    "verify_token_signature",
]
